name: "winrt-go build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # tests only run on windows
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.25.x
      - name: init
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.1
      - name: prepare
        run: make prepare
      - name: sanity-check
        run: make sanity-check
      - name: build
        run: make build
      - name: test
        run: make test
      - name: release
        if: github.ref == 'refs/heads/main'
        run: make release
      - name: clean
        run: |
          make clean

