name: "winrt-go test"

on:
  push:

jobs:

  # but tests only run on windows
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.25.x
      - name: init
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.1
      - name: test
        run: make test
